Make damage reduction from high defense depend on the monster's chance to hit.
When a monster attacks you, the defense score you need to get damage
reduction, instead of always being 10 (AC 0), is now 10 more than the
monster's chance-to-hit-you score.  Only the amount of excess defense
you have above and beyond this level counts toward damage reduction.

Exception:  if a monster has M3_VANDMGRDUC, then its chance to hit you
does not take away from your damage reduction:  you get the same
amount of reduction you would in vanilla.  Currently, the only
monsters with this flag are minotaurs.