Fix the Windows build:  build the net client by default.
It turns out the last remaining reason why Fourk wouldn't build on
Microsoft Windows is because of the change to not build the net client
by default.

If NETCLIENT is not defined, aimake running under Strawberry Perl on
MS Windows miscalculates the dependencies in a way that causes the
link stage to fail, as follows:

Building from nethack\src\main.c\main.o (rule link_c) failed: Command reported failure status 1, with the following command line:
C:\Strawberry\c\bin\g++.EXE -o nethack\src\main.c\main.exe nethack\src\main.c\main.o _aimake_get_option.o nethack\src\windows.c\windows.o nethack\src\menu.c\menu.o nethack\src\dialog.c\dialog.o nethack\src\options.c\options.o nethack\src\outchars.c\outchars.o nethack\src\keymap.c\keymap.o nethack\src\rungame.c\rungame.o nethack\src\motd.c\motd.o nethack\src\replay.c\replay.o nethack\src\topten.c\topten.o libnethack_common\src\menulist.c\menulist.o nethack\src\extrawin.c\extrawin.o nethack\src\sidebar.c\sidebar.o nethack\src\color.c\color.o nethack\src\getline.c\getline.o nethack\src\map.c\map.o nethack\src\gameover.c\gameover.o nethack\src\messages.c\messages.o nethack\src\status.c\status.o libnethack_common\src\utf8conv.c\utf8conv.o libnethack_common\src\common_options.c\common_options.o tilesets\src\tilesequence.c\tilesequence.o nethack\src\playerselect.c\playerselect.o libnethack\src\drawing.c\drawing.o nethack\src\brandings.c\brandings.o libnethack_common\src\hacklib.c\hacklib.o libnethack\src\objects.c\objects.o libnethack\src\symclass.c\symclass.o libnethack\src\monst.c\monst.o libnethack_common\src\xmalloc.c\xmalloc.o libuncursed\src\libuncursed.dll.a libnethack\libnethack.dll.a
and the following messages:
libnethack\libnethack.dll.a(dodis00006.o):(.text+0x0): multiple definition of `nh_get_drawing_info'
libnethack\src\drawing.c\drawing.o:c:/users/public/documents/tryfour/nhfourk/libnethack/src/drawing.c:430: first defined here
collect2.exe: error: ld returned 1 exit status

Defining NETCLIENT prevents this from happening.